# Generated by Django 3.0.5 on 2020-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, default='', max_length=240, null=True)),
                ('text', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('tags', models.CharField(blank=True, default='', max_length=240, null=True)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('link', models.CharField(blank=True, default='', max_length=480, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio/videos/')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('text', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
