# Generated by Django 3.0.5 on 2020-04-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200425_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/'),
        ),
    ]
