# Generated by Django 3.0.5 on 2020-04-26 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepage_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
